version: '3.8'
services:
  selenium:
    image: kynetiv/selenium-standalone-chromium-pi 
    hostname: selenium
    ports:
      - "4444:4444"
    environment: 
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped

  vgrical:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - selenium
    restart: unless-stopped